version: '3'

services:
  airflow:
    build: .
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@host.docker.internal/postgres
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    ports:
      - 8080:8080
    volumes:
      - ./volumes/dags:/opt/airflow/dags
      - ./volumes/logs:/opt/airflow/logs
      - ./volumes/plugins:/opt/airflow/plugins
    depends_on:
      - db

  airflow-init:
    image: apache/airflow:2.2.3
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@host.docker.internal/postgres
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
    command: >
      bash -c "airflow db init && airflow users create --username airflow --firstname airflow --lastname airflow --role Admin --email airflow@airflow.com -p airflow"
    depends_on:
      - db

  db:
    image: postgres:14.1-bullseye
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
